# Generated by Django 2.1.3 on 2018-11-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20181129_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
